export const GET_LEARNER_POSTS = "GET_LEARNER_POSTS";
export const CREATE_LEARNER_POST = "CREATE_LEARNER_POST";

export const GET_ADDRESS_SEARCH = "GET_ADDRESS_SEARCH";
export const INIT_ADDRESS = "INIT_ADDRESS";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
